test_that("regression tables delegate exact link inference and retain model context", {
  session <- nis_open()
  on.exit(nis_close(session))
  rows <- model_fixture()
  rows$group <- factor(rows$group, levels = c(0, 1, 2))
  rows$y[rows$HOSP_NIS == "0004"] <- NA
  design <- model_design(session, rows)
  design$design$variables$group <- rows$group
  fit <- fit_invented(design, y ~ x * group, missing = "exclude", df = Inf)
  original <- fit
  specification <- data.frame(id = c("interaction", "again", "base"),
    term = c("x:group1", "x:group1", "(Intercept)"), label = c("Interaction", "Repeat", "Constant"),
    unit = c("link", "link", "link"))
  spec_before <- specification
  tab <- nis_regression_table(fit, specification, "link")
  expect_s3_class(tab, "nis_regression_table")
  expect_identical(tab$data$id, c("interaction", "again", "base"))
  expect_identical(tab$data$term, c("x:group1", "x:group1", "(Intercept)"))
  expect_identical(tab$data$estimate, fit$coefficients$estimate[match(tab$data$term, fit$coefficients$term)])
  expect_identical(tab$data$se, fit$coefficients$se[match(tab$data$term, fit$coefficients$term)])
  expect_identical(tab$data$p_value, fit$coefficients$p_value[match(tab$data$term, fit$coefficients$term)])
  expect_identical(tab$model, original)
  expect_identical(fit, original)
  expect_identical(specification, spec_before)
  expect_identical(tab$factors, fit$factors)
  expect_identical(tab$sample, fit$sample)
  expect_identical(tab$diagnostics, fit$diagnostics)
  expect_identical(tab$provenance$model, fit$provenance)
  expect_identical(tab$data$coefficient_scale, rep("link", 3))
  expect_identical(tab$data$analysis_hospitals, rep(7, 3))
  expect_identical(tab$data$raw_missing, rep(8, 3))
  expect_identical(tab$data$disclosure_status, rep("unreviewed", 3))
  expect_identical(tab$provenance$scope, "experimental_numeric_regression_table")
  expect_identical(tab$provenance$analysis_ready, FALSE)
  expect_identical(tab$provenance$interval_scope, "pointwise")
  sum_rows <- model_fixture()
  sum_rows$group <- factor(sum_rows$group)
  sum_design <- model_design(session, sum_rows)
  sum_design$design$variables$group <- sum_rows$group
  contrasts(sum_design$design$variables$group) <- stats::contr.sum(2)
  sum_fit <- fit_invented(sum_design, y ~ group)
  sum_tab <- nis_regression_table(sum_fit, data.frame(id = c("g", "int"),
    term = c("group1", "(Intercept)"), label = c("Group", "Intercept"), unit = c("link", "link")), "link")
  expect_identical(sum_tab$factors, sum_fit$factors)
  expect_identical(sum_tab$factors$group$contrasts, sum_fit$factors$group$contrasts)
  domain <- nis_domain(design, "domain", "fail")
  domain_fit <- fit_invented(domain, y ~ x, missing = "exclude")
  domain_table <- nis_regression_table(domain_fit,
    data.frame(id = "x", term = "x", label = "Declared slope", unit = "link"), "link")
  expect_identical(domain_table$model$provenance$domains, domain$domains)
  expect_identical(domain_table$data$analysis_hospitals, 5)
  logical_rows <- model_fixture()
  logical_rows$logical_group <- logical_rows$group == 1
  logical_design <- model_design(session, logical_rows)
  logical_design$design$variables$logical_group <- logical_rows$logical_group
  logical_fit <- fit_invented(logical_design, y ~ logical_group)
  logical_table <- nis_regression_table(logical_fit, data.frame(id = "logical", term = "logical_groupTRUE",
    label = "Caller declaration", unit = "declared"), "link")
  expect_identical(logical_table$factors, logical_fit$factors)
})

test_that("aliases and undefined coefficient inference are preserved exactly", {
  session <- nis_open()
  on.exit(nis_close(session))
  rows <- model_fixture()
  rows$duplicate_x <- rows$x
  design <- model_design(session, rows)
  design$design$variables$duplicate_x <- rows$duplicate_x
  fit <- fit_invented(design, y ~ x + duplicate_x)
  expect_true(any(fit$coefficients$aliased))
  spec <- data.frame(id = "alias", term = fit$diagnostics$aliased[[1L]], label = "Alias", unit = "link")
  tab <- nis_regression_table(fit, spec, "link")
  at <- match(spec$term, fit$coefficients$term)
  expect_identical(tab$data$aliased, fit$coefficients$aliased[at])
  expect_identical(tab$data$estimate, fit$coefficients$estimate[at])
  expect_identical(tab$data$se, fit$coefficients$se[at])
  expect_identical(tab$data$statistic, fit$coefficients$statistic[at])
  expect_identical(tab$data$p_value, fit$coefficients$p_value[at])
  expect_identical(tab$data$lower, fit$coefficients$lower[at])
  expect_identical(tab$data$upper, fit$coefficients$upper[at])
  rows$y <- 0
  zero_fit <- fit_invented(model_design(session, rows), y ~ x)
  undefined <- nis_regression_table(zero_fit, data.frame(id = "x", term = "x", label = "Slope", unit = "link"), "link")
  expect_true(is.nan(undefined$data$statistic))
  expect_true(is.nan(undefined$data$p_value))
  reference_rows <- model_fixture()
  reference <- model_sandwich(reference_rows, y ~ x, stats::gaussian(), rep(TRUE, nrow(reference_rows)))
  plain_fit <- fit_invented(model_design(session, reference_rows), y ~ x)
  plain_table <- nis_regression_table(plain_fit, data.frame(id = c("slope", "int"),
    term = c("x", "(Intercept)"), label = c("Slope", "Intercept"), unit = c("link", "link")), "link")
  expect_equal(plain_table$data$estimate, unname(reference$coefficients[plain_table$data$term]), tolerance = 1e-9)
  expect_equal(plain_table$data$se, unname(sqrt(diag(reference$covariance))[match(plain_table$data$term, names(reference$coefficients))]), tolerance = 1e-8)
})

test_that("transformed responses and offsets retain original link model provenance", {
  session <- nis_open()
  on.exit(nis_close(session))
  design <- model_design(session, model_fixture())
  transformed <- fit_invented(design, log1p(abs(y)) ~ x)
  transformed_table <- nis_regression_table(transformed,
    data.frame(id = "x", term = "x", label = "Caller label", unit = "caller unit"), "link")
  expect_identical(transformed_table$data$estimate, transformed$coefficients$estimate[2L])
  expect_identical(transformed_table$model$provenance$response_expression, "log1p(abs(y))")
  expect_identical(transformed_table$data$family, "gaussian")
  design$design$variables$exposure <- seq_len(nrow(design$design$variables))
  offset_fit <- fit_invented(design, count ~ x + offset(log(exposure)), "quasipoisson")
  offset_table <- nis_regression_table(offset_fit,
    data.frame(id = "x", term = "x", label = "Rate?", unit = "arbitrary"), "link")
  expect_identical(offset_table$data$estimate, offset_fit$coefficients$estimate[2L])
  expect_identical(offset_table$model$provenance$offset, offset_fit$provenance$offset)
})

test_that("nonconverged model diagnostics remain visible and declarations are strict", {
  session <- nis_open()
  on.exit(nis_close(session))
  design <- model_design(session, model_fixture())
  design$design$variables$count <- ifelse(design$design$variables$x > 0, 1e60, 0)
  fit <- fit_invented(design, count ~ x, "quasipoisson")
  tab <- nis_regression_table(fit, data.frame(id = "x", term = "x", label = "x", unit = "link"), "link")
  expect_identical(tab$diagnostics, fit$diagnostics)
  expect_false(tab$diagnostics$converged)
  spec <- data.frame(id = "x", term = "x", label = "x", unit = "link")
  six <- cbind(spec, fifth = "extra", sixth = "extra")
  duplicate <- cbind(spec, id = "extra")
  five_duplicate <- cbind(spec, term = "extra")
  duplicate_id <- rbind(spec, spec)
  duplicate_id$id <- c("a", "a")
  expect_error(nis_regression_table(fit, six, "link"), "exactly")
  expect_error(nis_regression_table(fit, duplicate, "link"), "exactly")
  expect_error(nis_regression_table(fit, five_duplicate, "link"), "exactly")
  expect_error(nis_regression_table(fit, spec[, 1:3], "link"), "exactly")
  expect_error(nis_regression_table(fit, transform(spec, id = ""), "link"), "nonmissing, nonempty")
  expect_error(nis_regression_table(fit, transform(spec, term = "X"), "link"), "exactly match")
  expect_error(nis_regression_table(fit, duplicate_id, "link"), "unique")
  expect_error(nis_regression_table(fit, spec, "odds"), "Only scale")
  expect_error(nis_regression_table(fit, spec), "explicit")
  expect_error(nis_regression_table(fit, as.data.frame(lapply(spec, factor)), "link"), "plain character")
  expect_identical(spec$id, "x")
})
